name: snip-env
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.11.29=py37_0
  - cffi=1.11.5=py37he75722e_1
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.1=144
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - mkl=2019.1=144
  - mkl_fft=1.0.6=py37hd81dba3_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py37h6bb024c_1
  - numpy=1.15.4=py37h7e9f1db_0
  - numpy-base=1.15.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1a=h7b6447c_0
  - pillow=5.3.0=py37h34e0f95_0
  - pip=18.1=py37_0
  - pycparser=2.19=py37_0
  - python=3.7.1=h0371630_7
  - readline=7.0=h7b6447c_5
  - setuptools=40.6.2=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tqdm=4.28.1=py37h28b3542_0
  - wheel=0.32.3=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - ignite=0.1.2=py37_0
  - pytorch=1.0.0=py3.7_cuda9.0.176_cudnn7.4.1_1
  - torchvision=0.2.1=py_2
  - pip:
    - grpcio==1.17.1
    - markdown==3.0.1
    - protobuf==3.6.1
    - pytorch-ignite==0.1.2
    - tensorboard==1.12.1
    - tensorboardx==1.5
    - torch==1.0.0
    - torchsummary==1.5.1
    - werkzeug==0.14.1

